version: "3.9"
services:
    web1:
        image: web1:v1
        container_name: web1
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
#            - ASPNETCORE_URLS=http//+:80
        volumes:
            - /root/multiapp:/opt/app

        networks: 
            - multiappnet
            - nginxnet


networks:
    multiappnet:
        driver: bridge
    nginxnet:
        driver: bridge
