version: "3.9"
services:
    web1:
        image: web1:v1
        container_name: web1
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
#            - ASPNETCORE_URLS=http//+:80
        volumes:
            - /root/multiapp:/opt/app

        networks: 
            - multiappnet
            - nginxnet

        depends_on:
            - db
    web2:

        image: web2:v2
        container_name: web2
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
 #           - ASPNETCORE_URLS=http//+:80
        volumes:
            - /root/multiapp2/multiapp:/opt/app

        networks: 
            - multiappnet
            - nginxnet

        depends_on:
            - db
    web3:
        image: web3:v3
        container_name: web3
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
  #          - ASPNETCORE_URLS=http//+:80
        volumes:
            - /root/multiapp3/multiapp:/opt/app

        networks: 
            - multiappnet
            - nginxnet

        depends_on:
            - db


    db:
        image: "mcr.microsoft.com/mssql/server"
        container_name: db
        environment:
            SA_PASSWORD: "vV5r9tn0M4@"
            ACCEPT_EULA: "Y"
        ports:
          - "1433:1433"
        networks: 
            - multiappnet



    web-server:
        image: hub.hamdocker.ir/nginx:1.23.1
        ports:
            - "80:80"
        volumes:
            - /root/multiapp/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks: 
            - nginxnet 
        container_name: web-server


networks:
    multiappnet:
        driver: bridge
    nginxnet:
        driver: bridge
